#!/system/xbin/bash
clear
git clone https://github.com/amsitlab/smsid-java.git
cd ./smsid-java
chmod +x ./install
apt install ./smsid_1.1_all.deb
clear

toilet -f slant --gay "SPAMLITE"
sleep 1
echo "\033[33;1m Tools SPAM"
sleep 1
echo "\033[36;1m★""\033[34;1mIndonesian Power Security""\033[36;1m★"
sleep 1
echo "\033[32;1m Spam Yang Tersedia :"
echo "\033[35;1m1.""\033[36;1mBukalapak"
echo "\033[35;1m2.""\033[36;1mTelkomsel"
echo "\033[35;1m3.""\033[36;1mGrab"
echo "\033[35;1m4.""\033[36;1mTokopedia"
echo "\033[31;1m0. Keluar"
echo "\033[37;1m19.""\033[30;1mInformasi Tool Ini"
echo "\033[33;1m Pilih Angka:"
read mrrm

if [ $mrrm = 1 ] || [ $mrrm = 1 ]
then
clear
toilet -f slant "Bukalapak"
echo "\033[31;1mJenis Spam:""\033[37;1mChat WhatsApp"
echo "\033[31;1mBatas:""\033[37;1mUnlimited"
echo "\033[31;1mPemograman:""\033[37;1mPHP"
echo "\033[31;1mAuthor:""\033[37;1mSGB-Team"
sleep 5
clear
cd $HOME/LITESPAM/Tul/
php 1
fi

if
[ $mrrm = 2 ] || [ $mrrm = 2 ]
then
clear
echo "\033[31;1m"
toilet "T-Sel"
echo "\033[31;1mJenis Spam:""\033[37;1mSMS"
echo "\033[31;1mBatas:""\033[37;1mUnlimited"
echo "\033[31;1mPemograman:""\033[37;1mPHP"
echo "\033[31;1mAuthor:""\033[37;1mDanz"
sleep 5
clear
cd $HOME/LITESPAM/Tul/
php 2.php
fi

if [ $mrrm = 3 ] || [ $mrrm = 3 ]
then
clear
echo "\033[36;1m"
figlet "Grab"
echo "\033[31;1mJenis Spam:""\033[37;1mTelepon"
echo "\033[31;1mBatas:""\033[37;1mUnlimited"
echo "\033[31;1mPemograman:""\033[37;1mPHP"
echo "\033[31;1mAuthor:""\033[37;1mRaja Adtiya Candra"
sleep 5
clear
cd $HOME/LITESPAM/Tul/
php 3.php
fi


if [ $mrrm = 4 ] || [ $mrrm = 4 ]
then
clear
toilet -f mono9 -F gay "Tokopedia"
echo "\033[31;1mJenis Spam:""\033[37;1mTelepon"
echo "\033[31;1mBatas:""\033[37;1m1 Kali"
echo "\033[31;1mPemograman:""\033[37;1mPHP"
echo "\033[31;1mAuthor:""\033[37;1mSGB-Team"
sleep 5
clear
cd $HOME/LITESPAM/Tul/
php 4.php
fi


if
[ $mrrm = 19 ] || [ $mrrm = 19 ]
then
clear
toilet -f slant --gay "LiteSpam"
echo "\033[34;1mContact:""\033[37;1m https://fb.me/azis197"


sleep 1
echo "\033[35;1mPemograman:""\033[36;1m Bash"

echo "\033[33;1mKarya: Azis197"
sleep 1
echo "\033[32;1mVersi: v1"
sleep 1
echo "\033[36;1mTeam: Indonesia Power Security "
sleep 1
echo "\033[35;1mSpesial Thanks To: "
echo "\033[36;1m"Sukron M"
echo "Doublewow"
echo "Gobah"
echo "Solehudin"
echo "Nur Mu'ahidz"
echo "Power Lite Security"
sleep 1
echo "And All Member Indonesia Power Security"
echo "\033[30;1m tunggu 8 detik"
sleep 8
sh SPAM
fi

if
[ $mrrm = 0 ] || [ $mrrm = 0 ]
then
echo "\033[31;1m Keluar"
sleep 1
echo "\033[32;1m Sampai berjumpa lagi :)"
sleep 1
fi
